"""add contrasena to empleados

Revision ID: 98300c7ef18a
Revises: b447f6d75fef
Create Date: 2025-10-22 00:54:37.809486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98300c7ef18a'
down_revision = 'b447f6d75fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=200), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('contrasena_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False))
        batch_op.alter_column('correo',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###
