"""create empleado

Revision ID: b447f6d75fef
Revises: 9f37b049505f
Create Date: 2025-10-22 00:33:48.108563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b447f6d75fef'
down_revision = '9f37b049505f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('correo',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False))
        batch_op.alter_column('correo',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=False)
        batch_op.drop_column('contrasena_hash')

    # ### end Alembic commands ###
